import type { Monaco } from '@monaco-editor/react';

export const LIGHT_THEME = 'twexthub-light';
export const DARK_THEME = 'twexthub-dark';

// Hex values mirror the site palette in src/index.css (zinc/lilac/amber/rose/
// emerald scales plus the surface/ink tokens) so the editor reads as part of
// the page in both themes. Dark token colors reuse the site's established
// Prism code colors (the .token rules also applied to .markdown-body pre).
const LIGHT = {
  base: 'vs' as const,
  inherit: false,
  rules: [
    { token: 'comment', foreground: '8b8798', fontStyle: 'italic' },
    { token: 'string', foreground: '9e542d' },
    { token: 'string.escape', foreground: '7d4227' },
    { token: 'number', foreground: 'c26e39' },
    { token: 'constant', foreground: 'c26e39' },
    { token: 'regexp', foreground: 'c26e39' },
    { token: 'keyword', foreground: '8265b3' },
    { token: 'keyword.flow', foreground: '944239' },
    { token: 'type', foreground: '6d4f9e', fontStyle: 'italic' },
    { token: 'type.identifier', foreground: '3f6f5f' },
    { token: 'identifier', foreground: '262430' },
    { token: 'function', foreground: '3f6f5f' },
    { token: 'property', foreground: '55505f' },
    { token: 'variable', foreground: '262430' },
    { token: 'variable.predefined', foreground: '7d4227' },
    { token: 'variable.parameter', foreground: '55505f' },
    { token: 'operator', foreground: '55505f' },
    { token: 'delimiter', foreground: '55505f' },
    { token: 'tag', foreground: '944239' },
    { token: 'attribute.name', foreground: '6d4f9e' },
    { token: 'attribute.value', foreground: '9e542d' },
  ],
  colors: {
    'editor.background': '#fbfafd',
    'editor.foreground': '#262430',
    'editorLineNumber.foreground': '#a1a2b4',
    'editorLineNumber.activeForeground': '#55505f',
    'editor.selectionBackground': '#ddd1ec',
    'editor.inactiveSelectionBackground': '#ece4f5',
    'editor.lineHighlightBackground': '#f6f6f8',
    'editor.lineHighlightBorder': '#00000000',
    'editorCursor.foreground': '#6d4f9e',
    'editorIndentGuide.background': '#e0dde9',
    'editorIndentGuide.activeBackground': '#c3c4d0',
    'editorWidget.background': '#ffffff',
    'editorWidget.border': '#e0dde9',
    'input.background': '#ffffff',
    'input.border': '#e0dde9',
    'dropdown.background': '#ffffff',
    'dropdown.border': '#e0dde9',
    'scrollbarSlider.background': '#c3c4d080',
    'scrollbarSlider.hoverBackground': '#a1a2b480',
    'scrollbarSlider.activeBackground': '#83849a80',
    'editorGutter.background': '#fbfafd',
    'editorOverviewRuler.border': '#00000000',
    'editorBracketMatch.background': '#ece4f5',
    'editorBracketMatch.border': '#c9b6e2',
    'editorError.foreground': '#b4554a',
    'editorWarning.foreground': '#dc894c',
    'editor.hoverHighlightBackground': '#f5f1fa',
  },
};

const DARK = {
  base: 'vs-dark' as const,
  inherit: false,
  rules: [
    { token: 'comment', foreground: '9f97b4', fontStyle: 'italic' },
    { token: 'string', foreground: 'c3e88d' },
    { token: 'string.escape', foreground: 'ffcb6b' },
    { token: 'number', foreground: 'f78c6c' },
    { token: 'constant', foreground: 'f78c6c' },
    { token: 'regexp', foreground: 'ffcb6b' },
    { token: 'keyword', foreground: 'c792ea' },
    { token: 'keyword.flow', foreground: 'ff8b98' },
    { token: 'type', foreground: 'b29cd6', fontStyle: 'italic' },
    { token: 'type.identifier', foreground: '82aaff' },
    { token: 'identifier', foreground: 'ece8f5' },
    { token: 'function', foreground: '82aaff' },
    { token: 'property', foreground: 'a9a2ba' },
    { token: 'variable', foreground: 'ece8f5' },
    { token: 'variable.predefined', foreground: 'f78c6c' },
    { token: 'variable.parameter', foreground: 'a9a2ba' },
    { token: 'operator', foreground: '89ddff' },
    { token: 'delimiter', foreground: 'a9a2ba' },
    { token: 'tag', foreground: 'ff8b98' },
    { token: 'attribute.name', foreground: 'c792ea' },
    { token: 'attribute.value', foreground: 'c3e88d' },
  ],
  colors: {
    'editor.background': '#1b1726',
    'editor.foreground': '#ece8f5',
    'editorLineNumber.foreground': '#54556a',
    'editorLineNumber.activeForeground': '#a9a2ba',
    'editor.selectionBackground': '#4d3a70',
    'editor.inactiveSelectionBackground': '#342750',
    'editor.lineHighlightBackground': '#282235',
    'editor.lineHighlightBorder': '#00000000',
    'editorCursor.foreground': '#c9b6e2',
    'editorIndentGuide.background': '#302a42',
    'editorIndentGuide.activeBackground': '#4d3a70',
    'editorWidget.background': '#201b2c',
    'editorWidget.border': '#302a42',
    'input.background': '#201b2c',
    'input.border': '#302a42',
    'dropdown.background': '#201b2c',
    'dropdown.border': '#302a42',
    'scrollbarSlider.background': '#54556a80',
    'scrollbarSlider.hoverBackground': '#6b6c8280',
    'scrollbarSlider.activeBackground': '#83849a80',
    'editorGutter.background': '#1b1726',
    'editorOverviewRuler.border': '#00000000',
    'editorBracketMatch.background': '#342750',
    'editorBracketMatch.border': '#6d4f9e',
    'editorError.foreground': '#cb6f63',
    'editorWarning.foreground': '#e7a269',
    'editor.hoverHighlightBackground': '#282235',
  },
};

export function defineMonacoThemes(monaco: Monaco): void {
  monaco.editor.defineTheme(LIGHT_THEME, LIGHT);
  monaco.editor.defineTheme(DARK_THEME, DARK);
}
